const mongoose = require('mongoose')
const { Pricing } = require('./models')

async function funB() {
  try {
    const conn = await mongoose.connect(`mongodb://localhost:27017/test2`, {
      autoReconnect: true,
      reconnectTries: 10,
      reconnectInterval: 100
    })

    await Pricing.remove()

    let data = [
      { '_id': '82', 'countryId': '82', 'countryName': "Korea, South", 'sms': 20, 'lms': 50, 'mms': 200, 'ata': 19, 'cta': 13, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '670', 'countryId': '670', 'countryName': "East Timor", 'sms': 180, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '239', 'countryId': '239', 'countryName': "Sao Tome and Principe", 'sms': 271, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '993', 'countryId': '993', 'countryName': "Turkmenistan", 'sms': 94, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '262', 'countryId': '262', 'countryName': "Reunion Island", 'sms': 349, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '370', 'countryId': '370', 'countryName': "Lithuania", 'sms': 94, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '855', 'countryId': '855', 'countryName': "Cambodia", 'sms': 94, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '242', 'countryId': '242', 'countryName': "Republic Of The 'Congo", 'sms': 80, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '41', 'countryId': '41', 'countryName': "Switzerland", 'sms': 156, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '251', 'countryId': '251', 'countryName': "Ethiopia", 'sms': 94, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '297', 'countryId': '297', 'countryName': "Aruba", 'sms': 104, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '268', 'countryId': '268', 'countryName': "Swaziland", 'sms': 124, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '54', 'countryId': '54', 'countryName': "Argentina", 'sms': 104, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '591', 'countryId': '591', 'countryName': "Bolivia", 'sms': 94, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '237', 'countryId': '237', 'countryName': "Cameroon", 'sms': 104, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '226', 'countryId': '226', 'countryName': "Burkina 'Faso", 'sms': 104, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '973', 'countryId': '973', 'countryName': "Bahrain", 'sms': 102, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '966', 'countryId': '966', 'countryName': "Saudi 'Arabia", 'sms': 102, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '596', 'countryId': '596', 'countryName': "Martinique", 'sms': 297, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '691', 'countryId': '691', 'countryName': "Micronesia", 'sms': 145, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '81', 'countryId': '81', 'countryName': "Japan", 'sms': 90, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '238', 'countryId': '238', 'countryName': "Cape 'Verde", 'sms': 90, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '386', 'countryId': '386', 'countryName': "Slovenia", 'sms': 94, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '502', 'countryId': '502', 'countryName': "Guatemala", 'sms': 94, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '387', 'countryId': '387', 'countryName': "Bosnia and 'Herzegovina", 'sms': 104, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '965', 'countryId': '965', 'countryName': "Kuwait", 'sms': 104, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '962', 'countryId': '962', 'countryName': "Jordan", 'sms': 104, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '1767', 'countryId': '1767', 'countryName': "Dominica", 'sms': 94, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '231', 'countryId': '231', 'countryName': "Liberia", 'sms': 104, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '960', 'countryId': '960', 'countryName': "Maldives", 'sms': 94, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '1876', 'countryId': '1876', 'countryName': "Jamaica", 'sms': 94, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '968', 'countryId': '968', 'countryName': "Oman", 'sms': 102, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '255', 'countryId': '255', 'countryName': "Tanzania", 'sms': 104, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '84', 'countryId': '84', 'countryName': "Vietnam", 'sms': 104, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '225', 'countryId': '225', 'countryName': "Ivory 'Coast", 'sms': 94, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '299', 'countryId': '299', 'countryName': "Greenland", 'sms': 94, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '241', 'countryId': '241', 'countryName': "Gabon", 'sms': 94, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '508', 'countryId': '508', 'countryName': "Saint Pierre and 'Miquelon", 'sms': 129, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '377', 'countryId': '377', 'countryName': "Monaco", 'sms': 108, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '681', 'countryId': '681', 'countryName': "Wallis and 'Futuna", 'sms': 129, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '64', 'countryId': '64', 'countryName': "New 'Zealand", 'sms': 110, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '967', 'countryId': '967', 'countryName': "Yemen", 'sms': 94, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '376', 'countryId': '376', 'countryName': "Andorra", 'sms': 90, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '355', 'countryId': '355', 'countryName': "Albania", 'sms': 118, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '685', 'countryId': '685', 'countryName': "Samoa", 'sms': 94, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '853', 'countryId': '853', 'countryName': "Macau", 'sms': 104, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '971', 'countryId': '971', 'countryName': "United Arab 'Emirates", 'sms': 104, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '1671', 'countryId': '1671', 'countryName': "Guam", 'sms': 94, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '383', 'countryId': '383', 'countryName': "Kosovo", 'sms': 194, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '91', 'countryId': '91', 'countryName': "India", 'sms': 98, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '994', 'countryId': '994', 'countryName': "Azerbaijan", 'sms': 118, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '266', 'countryId': '266', 'countryName': "Lesotho", 'sms': 108, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '1340', 'countryId': '1340', 'countryName': "Virgin Islands, US", 'sms': 104, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '254', 'countryId': '254', 'countryName': "Kenya", 'sms': 108, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '992', 'countryId': '992', 'countryName': "Tajikistan", 'sms': 94, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '90', 'countryId': '90', 'countryName': "Turkey", 'sms': 102, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '93', 'countryId': '93', 'countryName': "Afghanistan", 'sms': 94, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '880', 'countryId': '880', 'countryName': "Bangladesh", 'sms': 102, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '677', 'countryId': '677', 'countryName': "Solomon 'Islands", 'sms': 166, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '1649', 'countryId': '1649', 'countryName': "Turks and Caicos 'Islands", 'sms': 90, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '1758', 'countryId': '1758', 'countryName': "Saint 'Lucia", 'sms': 104, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '378', 'countryId': '378', 'countryName': "San 'Marino", 'sms': 155, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '689', 'countryId': '689', 'countryName': "French 'Polynesia", 'sms': 168, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '33', 'countryId': '33', 'countryName': "France", 'sms': 210, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '1441', 'countryId': '1441', 'countryName': "Bermuda", 'sms': 94, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '421', 'countryId': '421', 'countryName': "Slovakia", 'sms': 110, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '252', 'countryId': '252', 'countryName': "Somalia", 'sms': 139, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '51', 'countryId': '51', 'countryName': "Peru", 'sms': 104, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '856', 'countryId': '856', 'countryName': "Laos", 'sms': 94, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '674', 'countryId': '674', 'countryName': "Nauru", 'sms': 155, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '248', 'countryId': '248', 'countryName': "Seychelles", 'sms': 94, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '47', 'countryId': '47', 'countryName': "Norway", 'sms': 130, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '265', 'countryId': '265', 'countryName': "Malawi", 'sms': 94, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '682', 'countryId': '682', 'countryName': "Cook 'Islands", 'sms': 94, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '229', 'countryId': '229', 'countryName': "Benin", 'sms': 108, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '382', 'countryId': '382', 'countryName': "Montenegro", 'sms': 104, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '1869', 'countryId': '1869', 'countryName': "Saint Kitts and 'Nevis", 'sms': 104, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '228', 'countryId': '228', 'countryName': "Togo", 'sms': 94, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '86', 'countryId': '86', 'countryName': "China", 'sms': 100, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '374', 'countryId': '374', 'countryName': "Armenia", 'sms': 94, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '1809', 'countryId': '1809', 'countryName': "Dominican 'Republic", 'sms': 132, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '380', 'countryId': '380', 'countryName': "Ukraine", 'sms': 104, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '233', 'countryId': '233', 'countryName': "Ghana", 'sms': 94, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '676', 'countryId': '676', 'countryName': "Tonga", 'sms': 103, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '1345', 'countryId': '1345', 'countryName': "Cayman 'Islands", 'sms': 94, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '218', 'countryId': '218', 'countryName': "Libya", 'sms': 106, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '358', 'countryId': '358', 'countryName': "Finland", 'sms': 114, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '236', 'countryId': '236', 'countryName': "Central African 'Republic", 'sms': 35, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '230', 'countryId': '230', 'countryName': "Mauritius", 'sms': 104, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '423', 'countryId': '423', 'countryName': "Liechtenstein", 'sms': 94, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '61', 'countryId': '61', 'countryName': "Australia", 'sms': 108, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '223', 'countryId': '223', 'countryName': "Mali", 'sms': 90, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '7', 'countryId': '7', 'countryName': "Russia", 'sms': 104, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '359', 'countryId': '359', 'countryName': "Bulgaria", 'sms': 104, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '1', 'countryId': '1', 'countryName': "United 'States", 'sms': 90, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '40', 'countryId': '40', 'countryName': "Romania", 'sms': 108, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '244', 'countryId': '244', 'countryName': "Angola", 'sms': 104, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '235', 'countryId': '235', 'countryName': "Chad", 'sms': 94, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '27', 'countryId': '27', 'countryName': "South 'Africa", 'sms': 104, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '357', 'countryId': '357', 'countryName': "Cyprus", 'sms': 94, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '46', 'countryId': '46', 'countryName': "Sweden", 'sms': 134, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '974', 'countryId': '974', 'countryName': "Qatar", 'sms': 106, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '60', 'countryId': '60', 'countryName': "Malaysia", 'sms': 104, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '43', 'countryId': '43', 'countryName': "Austria", 'sms': 176, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '258', 'countryId': '258', 'countryName': "Mozambique", 'sms': 94, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '256', 'countryId': '256', 'countryName': "Uganda", 'sms': 104, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '36', 'countryId': '36', 'countryName': "Hungary", 'sms': 168, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '227', 'countryId': '227', 'countryName': "Niger", 'sms': 90, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '211', 'countryId': '211', 'countryName': "South 'Sudan", 'sms': 80, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '55', 'countryId': '55', 'countryName': "Brazil", 'sms': 106, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '298', 'countryId': '298', 'countryName': "Faroe 'Islands", 'sms': 90, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '224', 'countryId': '224', 'countryName': "Guinea", 'sms': 104, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '507', 'countryId': '507', 'countryName': "Panama", 'sms': 94, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '506', 'countryId': '506', 'countryName': "Costa 'Rica", 'sms': 106, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '352', 'countryId': '352', 'countryName': "Luxembourg", 'sms': 94, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '1684', 'countryId': '1684', 'countryName': "American 'Samoa", 'sms': 233, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '1242', 'countryId': '1242', 'countryName': "Bahamas", 'sms': 102, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '1784', 'countryId': '1784', 'countryName': "Saint Vincent and The 'Grenadines", 'sms': 103, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '350', 'countryId': '350', 'countryName': "Gibraltar", 'sms': 90, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '353', 'countryId': '353', 'countryName': "Ireland", 'sms': 104, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '92', 'countryId': '92', 'countryName': "Pakistan", 'sms': 106, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '680', 'countryId': '680', 'countryName': "Palau", 'sms': 145, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '234', 'countryId': '234', 'countryName': "Nigeria", 'sms': 102, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '593', 'countryId': '593', 'countryName': "Ecuador", 'sms': 104, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '1670', 'countryId': '1670', 'countryName': "Northern Mariana 'Islands", 'sms': 152, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '673', 'countryId': '673', 'countryName': "Brunei", 'sms': 106, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '375', 'countryId': '375', 'countryName': "Belarus", 'sms': 94, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '98', 'countryId': '98', 'countryName': "Iran", 'sms': 94, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '213', 'countryId': '213', 'countryName': "Algeria", 'sms': 104, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '503', 'countryId': '503', 'countryName': "El 'Salvador", 'sms': 104, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '420', 'countryId': '420', 'countryName': "Czechia", 'sms': 156, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '692', 'countryId': '692', 'countryName': "Marshall 'Islands", 'sms': 219, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '56', 'countryId': '56', 'countryName': "Chile", 'sms': 104, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '1787', 'countryId': '1787', 'countryName': "Puerto 'Rico", 'sms': 104, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '32', 'countryId': '32', 'countryName': "Belgium", 'sms': 168, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '66', 'countryId': '66', 'countryName': "Thailand", 'sms': 104, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '509', 'countryId': '509', 'countryName': "Haiti", 'sms': 94, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '501', 'countryId': '501', 'countryName': "Belize", 'sms': 102, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '852', 'countryId': '852', 'countryName': "Hong 'Kong", 'sms': 104, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '232', 'countryId': '232', 'countryName': "Sierra 'Leone", 'sms': 94, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '995', 'countryId': '995', 'countryName': "Georgia", 'sms': 104, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '220', 'countryId': '220', 'countryName': "Gambia", 'sms': 90, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '63', 'countryId': '63', 'countryName': "Philippines", 'sms': 98, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '373', 'countryId': '373', 'countryName': "Moldova", 'sms': 108, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '212', 'countryId': '212', 'countryName': "Morocco", 'sms': 132, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '385', 'countryId': '385', 'countryName': "Croatia", 'sms': 106, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '976', 'countryId': '976', 'countryName': "Mongolia", 'sms': 90, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '245', 'countryId': '245', 'countryName': "Guinea-'Bissau", 'sms': 104, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '686', 'countryId': '686', 'countryName': "Kiribati", 'sms': 55, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '264', 'countryId': '264', 'countryName': "Namibia", 'sms': 90, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '1473', 'countryId': '1473', 'countryName': "Grenada", 'sms': 94, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '964', 'countryId': '964', 'countryName': "Iraq", 'sms': 102, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '351', 'countryId': '351', 'countryName': "Portugal", 'sms': 182, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '372', 'countryId': '372', 'countryName': "Estonia", 'sms': 106, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '598', 'countryId': '598', 'countryName': "Uruguay", 'sms': 104, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '52', 'countryId': '52', 'countryName': "Mexico", 'sms': 90, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '961', 'countryId': '961', 'countryName': "Lebanon", 'sms': 104, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '998', 'countryId': '998', 'countryName': "Uzbekistan", 'sms': 104, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '216', 'countryId': '216', 'countryName': "Tunisia", 'sms': 94, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '253', 'countryId': '253', 'countryName': "Djibouti", 'sms': 90, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '250', 'countryId': '250', 'countryName': "Rwanda", 'sms': 94, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '1268', 'countryId': '1268', 'countryName': "Antigua and 'Barbuda", 'sms': 104, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '34', 'countryId': '34', 'countryName': "Spain", 'sms': 190, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '57', 'countryId': '57', 'countryName': "Colombia", 'sms': 106, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '257', 'countryId': '257', 'countryName': "Burundi", 'sms': 94, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '886', 'countryId': '886', 'countryName': "Taiwan", 'sms': 122, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '679', 'countryId': '679', 'countryName': "Fiji", 'sms': 94, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '1246', 'countryId': '1246', 'countryName': "Barbados", 'sms': 94, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '261', 'countryId': '261', 'countryName': "Madagascar", 'sms': 94, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '39', 'countryId': '39', 'countryName': "Italy", 'sms': 178, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '599', 'countryId': '599', 'countryName': "Curacao", 'sms': 103, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '975', 'countryId': '975', 'countryName': "Bhutan", 'sms': 96, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '249', 'countryId': '249', 'countryName': "Sudan", 'sms': 94, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '977', 'countryId': '977', 'countryName': "Nepal", 'sms': 102, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '356', 'countryId': '356', 'countryName': "Malta", 'sms': 90, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '243', 'countryId': '243', 'countryName': "Democratic Republic of the 'Congo", 'sms': 104, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '31', 'countryId': '31', 'countryName': "Netherlands", 'sms': 180, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '597', 'countryId': '597', 'countryName': "Suriname", 'sms': 94, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '1264', 'countryId': '1264', 'countryName': "Anguilla", 'sms': 94, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '58', 'countryId': '58', 'countryName': "Venezuela", 'sms': 94, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '972', 'countryId': '972', 'countryName': "Israel", 'sms': 94, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '62', 'countryId': '62', 'countryName': "Indonesia", 'sms': 110, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '354', 'countryId': '354', 'countryName': "Iceland", 'sms': 94, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '260', 'countryId': '260', 'countryName': "Zambia", 'sms': 108, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '221', 'countryId': '221', 'countryName': "Senegal", 'sms': 94, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '675', 'countryId': '675', 'countryName': "Papua New 'Guinea", 'sms': 90, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '1868', 'countryId': '1868', 'countryName': "Trinidad and 'Tobago", 'sms': 94, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '263', 'countryId': '263', 'countryName': "Zimbabwe", 'sms': 104, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '49', 'countryId': '49', 'countryName': "Germany", 'sms': 188, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '678', 'countryId': '678', 'countryName': "Vanuatu", 'sms': 104, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '45', 'countryId': '45', 'countryName': "Denmark", 'sms': 114, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '48', 'countryId': '48', 'countryName': "Poland", 'sms': 162, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '222', 'countryId': '222', 'countryName': "Mauritania", 'sms': 108, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '996', 'countryId': '996', 'countryName': "Kyrgyzstan", 'sms': 94, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '970', 'countryId': '970', 'countryName': "Palestinian 'Territory", 'sms': 145, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '1664', 'countryId': '1664', 'countryName': "Montserrat", 'sms': 105, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '687', 'countryId': '687', 'countryName': "New 'Caledonia", 'sms': 323, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '389', 'countryId': '389', 'countryName': "Macedonia", 'sms': 108, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '94', 'countryId': '94', 'countryName': "Sri 'Lanka", 'sms': 104, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '371', 'countryId': '371', 'countryName': "Latvia", 'sms': 118, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '1721', 'countryId': '1721', 'countryName': "Sint Maarten (Dutch Part')", 'sms': 103, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '592', 'countryId': '592', 'countryName': "Guyana", 'sms': 94, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '963', 'countryId': '963', 'countryName': "Syria", 'sms': 104, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '590', 'countryId': '590', 'countryName': "Guadeloupe", 'sms': 327, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '504', 'countryId': '504', 'countryName': "Honduras", 'sms': 108, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '95', 'countryId': '95', 'countryName': "Myanmar", 'sms': 235, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '240', 'countryId': '240', 'countryName': "Equatorial 'Guinea", 'sms': 94, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '20', 'countryId': '20', 'countryName': "Egypt", 'sms': 104, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '505', 'countryId': '505', 'countryName': "Nicaragua", 'sms': 94, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '65', 'countryId': '65', 'countryName': "Singapore", 'sms': 108, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '381', 'countryId': '381', 'countryName': "Serbia", 'sms': 104, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '267', 'countryId': '267', 'countryName': "Botswana", 'sms': 104, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '44', 'countryId': '44', 'countryName': "United 'Kingdom", 'sms': 110, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '1284', 'countryId': '1284', 'countryName': "Virgin Islands, British", 'sms': 103, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '30', 'countryId': '30', 'countryName': "Greece", 'sms': 182, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '595', 'countryId': '595', 'countryName': "Paraguay", 'sms': 94, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '594', 'countryId': '594', 'countryName': "French 'Guiana", 'sms': 108, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() },
      { '_id': '269', 'countryId': '269', 'countryName': "Comoros", 'sms': 94, 'lms': 500, 'mms': 1000, 'dateCreated': new Date(), 'dateUpdated': new Date() }
    ]
    await Pricing.insertMany(data)

    console.log(await Pricing.count())
    console.log('Success')
    mongoose.connection.close()
  } catch (ERR) {
    console.log('check ERR', ERR)
    mongoose.connection.close()
  }
}

funB()
